---
title: "US post offices"
author: "Navid Mohseni"
date: "4/14/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(scales)
library(tidytuesdayR)
theme_set(theme_light())

```

```{r}
tt <- tt_load("2021-04-13")
tt$post_offices

tt$post_offices %>% 
  add_count(name, orig_name, state, county1, sort = TRUE) %>% 
  filter(n >= 2) %>% 
  arrange(name, orig_name, state, county1)

post_offices <- tt$post_offices %>% 
  select(name, state, county1, established, discontinued, continuous,
         stamp_index, id, coordinates, latitude, longitude, gnis_dist, 
         gnis_county, gnis_state) %>% 
  filter(established >= 1639,
    discontinued <= 2021)


post_office_years <- tt$post_offices %>% 
  select(name, state, established, discontinued) %>% 
  replace_na(list(discontinued = 2003)) %>%
  mutate(year = map2(established, discontinued, seq)) %>% 
  unnest(year)


```

```{r}
post_offices %>% 
  filter(!is.na(discontinued)) %>% 
  count(state, 
        decade = 10 * (discontinued %/% 10 ),
        name = "n_closures")
```

